#!/usr/bin/env bash
# Bash script that displays 'Best School' 10 times, but 'Hi' at 9th itr

i=0
while [ "$i" -le 10 ]
do
	if [ "$i" -eq 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	i=$(( i + 1 ))
done
