#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes

min=1
echo "Hour: 0"
while [ "$min" -le 59 ]
do
	echo "$min"
	min=$(( min + 1 ))
done

hr=1
echo "Hour: 1"
while [ "$hr" -le 12 ]
do
        echo "$hr"
        hr=$(( hr + 1 ))
done
